window.METAMORPHOSIS_WEEK1={
  book:{
    title:'THE METAMORPHOSIS',
    author:'Franz Kafka',
    cefr:'A1',
    adaptation_note_pt:'Adaptação educacional com inglês simplificado. O enredo, a atmosfera sombria, os conflitos, a filosofia e o final da obra são preservados.',
    cover_asset:'assets/cover_the_metamorphosis_a1.png'
  },
  week:{
    title:'A Strange Morning',
    before_you_read:[
      'What do you usually think about first when you wake up?',
      'Is being late for work or school stressful for you?',
      'Can a person work too much? Why?'
    ],
    opening_illustration:{
      asset:'assets/week1_opening_gregor_wakes.png',
      alt_text:'Gregor is in his bedroom on a gray morning. His body has changed into a large insect-like form. The bed, window, desk and clock are visible around him.'
    },
    story:[
      'Gregor Samsa opens his eyes.',
      'It is morning.',
      'His bedroom is quiet, and the light outside the window is gray.',
      'Gregor is in his bed.',
      'But something is very wrong.',
      'His body is different.',
      'It is not the body he knows.',
      'Gregor tries to move.',
      'It is difficult.',
      'He looks down at himself and does not understand what he sees.',
      'For a moment, he is silent.',
      'Then he looks around the room.',
      'His desk is there.',
      'His clothes are there.',
      'A picture is on the wall.',
      'Everything in the room is normal.',
      'Only Gregor is different.',
      'He looks at the clock.',
      'His eyes open wide.',
      '“Oh no,” he thinks. “I am late.”',
      'Gregor works as a traveling salesman.',
      'He travels a lot for his job.',
      'He takes trains early in the morning and returns home tired.',
      'He does not like his job.',
      'The work is difficult.',
      'His manager is demanding.',
      'The traveling is tiring.',
      'But Gregor cannot simply leave his job.',
      'His family needs money.',
      'Gregor helps his mother, his father and his younger sister, Grete.',
      'He thinks about work again.',
      '“Maybe I can take the next train.”',
      'He tries to get out of bed.',
      'He cannot.',
      'His new body does not move like his old body.',
      'Gregor tries again.',
      'Nothing.',
      "Then he hears his mother's voice outside the bedroom.",
      '“Gregor? It is almost seven. Are you going to work?”',
      'Gregor tries to answer.',
      '“Yes, Mother. I am getting ready.”',
      'But his voice sounds strange.',
      'Gregor stops.',
      'That is not his normal voice.',
      'Outside the room, there is silence.',
      'Then Grete speaks.',
      '“Gregor? Are you OK?”',
      '“I am fine,” Gregor says.',
      'But he is not fine.',
      'His father calls from another door.',
      '“Gregor, what is happening?”',
      'Gregor becomes more worried.',
      'He needs to leave the bedroom.',
      'He needs to go to work.',
      'He needs to explain everything.',
      'But how can he explain something that he does not understand?',
      'He looks at the clock again.',
      'Time is passing.',
      'His train is gone.',
      'His family is waiting.',
      'His office is waiting too.',
      'Then Gregor hears a new sound.',
      'Ding-dong.',
      'The doorbell.',
      'Someone is at the apartment door.',
      'Gregor listens.',
      'He hears his father walking through the apartment.',
      "Then he hears another man's voice.",
      'Gregor knows that voice.',
      'His body becomes still.',
      'The visitor is from his office.',
      'It is the chief clerk.',
      'Gregor is not at work.',
      'So work has come to Gregor.'
    ],
    true_false:[
      {statement:'Gregor wakes up in a hotel.',answer:false},
      {statement:"Gregor's body is different.",answer:true},
      {statement:'Gregor is worried because he is late for work.',answer:true},
      {statement:'Gregor loves traveling for his job.',answer:false},
      {statement:'Gregor helps his family financially.',answer:true},
      {statement:"Grete is Gregor's sister.",answer:true},
      {statement:"A person from Gregor's office comes to the apartment.",answer:true}
    ],
    vocabulary:[
      {word:'wake up',pt:'acordar'},
      {word:'bed',pt:'cama'},
      {word:'room / bedroom',pt:'quarto'},
      {word:'clock',pt:'relógio'},
      {word:'late',pt:'atrasado'},
      {word:'work',pt:'trabalho / trabalhar'},
      {word:'train',pt:'trem'},
      {word:'door',pt:'porta'},
      {word:'voice',pt:'voz'},
      {word:'worried',pt:'preocupado'},
      {word:'tired',pt:'cansado'},
      {word:'strange',pt:'estranho'}
    ],
    visual_reflection:{
      title:'The Closed Door',
      asset:'assets/week1_visual_reflection_closed_door.png',
      alt_text:'Gregor is inside his dark bedroom near the bed. A wooden doorway separates him from Mrs. Samsa, Mr. Samsa and Grete, who stand in the brighter hallway looking worried.',
      questions:['Where is Gregor?','How does the family look?','Why is the closed door important in this scene?']
    },
    reflection:{
      title:'Think About the Story',
      prompt:'Why does Gregor think about work before he thinks deeply about his transformation?',
      sentence_starter:'I think Gregor thinks about work because...'
    },
    writing_mission:{
      title:"Gregor's Morning",
      word_target:'20–30 words',
      instruction:"Write about Gregor's morning.",
      sentence_starters:['Gregor is...','He is in...','His body is...','He is worried because...','His family...']
    },
    next_week:{chapter:'Chapter 2 — Behind the Door',teaser:'Gregor cannot stay hidden forever.'}
  }
};
